os: linux
dist: xenial
language: clojure
lein: 2.7.1
jdk:
  - openjdk8
stages:
  - test
  - deploy
jobs:
  include:
    - stage: "test"
      script: lein test
    - stage: "deploy"
      script: lein jar
      if: fork = false AND tag =~ ^(\d+)\.(\d+)\.(\d+)(-.+)?$
