language: clojure
lein: 2.7.1
script:
  - lein test
jdk:
  - openjdk8

jobs:
  include:
    - stage: ":ship: it to clojars"
      script: lein jar
      if: fork = false AND tag =~ ^(\d+)\.(\d+)\.(\d+)(-.+)?$
